FROM ianchi74/openwrt:luci-19.07.1

# add luci2 files
COPY ipk/*.ipk /tmp/ipk/
COPY share /usr/share/
COPY uhttpd /etc/uhttpd/

RUN cd /www && mkdir luci2
RUN opkg --force-reinstall install /tmp/ipk/*.ipk && \
    rm -rf /tmp/ipk 
