#!/bin/sh
#
# Copyright © 2017 OpenWrt.org
#
. /lib/functions/system.sh
. /lib/functions/uci-defaults.sh
board_config_update

        ucidef_set_interface_wan "eth0" "static"

board_config_flush
exit 0