#!/bin/sh

uci set network.wan.ipaddr=172.17.0.2
uci set network.wan.netmask=255.255.255.0
uci set network.wan.gateway=172.17.0.1
uci set network.wan.proto=static

uci set dhcp.@dnsmasq[0].resolvfile='/etc/resolv.conf'

uci commit 


exit 0
